require: rubocop-rspec
AllCops:
    NewCops: enable
    TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - valvat.gemspec
    - spec/**/*_spec.rb

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/StringChars:
    Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Enabled: false
