require: rubocop-rspec
AllCops:
    NewCops: enable

Metrics/BlockLength:
  Exclude:
    - valvat.gemspec
    - spec/**/*_spec.rb

Style/Documentation:
    Enabled: false

RSpec/MultipleExpectations:
    Enabled: false

RSpec/ExampleLength:
    Enabled: false